<?php
// module/Message/view/message/message/index.phtml:

$title = 'My messages';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('message', ['action' => 'add']) ?>">Add new message</a>
</p>

<table class="table">
<tr>
    <th>Message</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($messages as $message) : ?>
    <tr>
        <td><?= $this->escapeHtml($message->message) ?></td>
        <td>
            <a href="<?= $this->url('message', ['action' => 'edit', 'id' => $message->id]) ?>">Edit</a>
            <a href="<?= $this->url('message', ['action' => 'delete', 'id' => $message->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
